require("plugins.packer")

require("plugins.bufferline")
require("plugins.colorsceme")
require("plugins.comment")
require("plugins.dap")
require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.lsp_signature")
require("plugins.nvim-autopairs")
require("plugins.nvim-colorizer")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.windows")
